# Generated by Django 4.1.6 on 2023-02-15 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_compressedimage_originalimg"),
    ]

    operations = [
        migrations.CreateModel(
            name="OriginalImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("orig_img_url", models.ImageField(upload_to="images")),
            ],
        ),
        migrations.RenameField(
            model_name="compressedimage",
            old_name="imgUrl",
            new_name="comp_img_url",
        ),
        migrations.RemoveField(
            model_name="compressedimage",
            name="originalImg",
        ),
        migrations.DeleteModel(
            name="UploadImage",
        ),
        migrations.AddField(
            model_name="compressedimage",
            name="orig_img",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.originalimage",
            ),
        ),
    ]
